const SIZE=10;
const SHAPES={square:{name:'Квадрат 2×2',cells:[[0,0],[1,0],[0,1],[1,1]],color:'yellow'},line4:{name:'Линия 4',cells:[[0,0],[0,1],[0,2],[0,3]],color:'blue'},L:{name:'L',cells:[[0,0],[0,1],[0,2],[1,2]],color:'orange'},Z:{name:'Z',cells:[[0,0],[1,0],[1,1],[2,1]],color:'red'},J:{name:'J',cells:[[1,0],[1,1],[1,2],[0,2]],color:'pink'},S:{name:'S',cells:[[1,0],[2,0],[0,1],[1,1]],color:'green'},T:{name:'T',cells:[[0,0],[1,0],[2,0],[1,1]],color:'purple'}};
const IDS=Object.keys(SHAPES);let board=emptyBoard(),tool='block',slots=[null,null,null],slotOri=[0,0,0],activeSlot=0,lastImage=null,suggestion=null;
const $=id=>document.getElementById(id),boardEl=$('board');
function emptyBoard(){return Array.from({length:SIZE},()=>Array(SIZE).fill(0))}
function key(c){return JSON.stringify(c.slice().sort((a,b)=>a[1]-b[1]||a[0]-b[0]))}
function rotate(c){const o=c.map(([x,y])=>[y,-x]),mx=Math.min(...o.map(p=>p[0])),my=Math.min(...o.map(p=>p[1]));return o.map(([x,y])=>[x-mx,y-my])}
function orientations(c){let out=[],cur=c;for(let i=0;i<4;i++){const k=key(cur);if(!out.some(x=>x.key===k))out.push({cells:cur,key:k});cur=rotate(cur)}return out}
const ORIENTS={};IDS.forEach(id=>ORIENTS[id]=orientations(SHAPES[id].cells));
function preview(id,o=0){const cells=ORIENTS[id][o].cells,w=Math.max(...cells.map(p=>p[0]))+1,h=Math.max(...cells.map(p=>p[1]))+1,d=document.createElement('div');d.className='shape '+SHAPES[id].color;d.style.gridTemplateColumns=`repeat(${w},12px)`;d.style.gridTemplateRows=`repeat(${h},12px)`;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=document.createElement('i');if(!cells.some(p=>p[0]===x&&p[1]===y))i.style.visibility='hidden';d.appendChild(i)}return d}
function renderBoard(){boardEl.innerHTML='';for(let r=0;r<10;r++)for(let c=0;c<10;c++){const e=document.createElement('div');e.className='cell';const v=board[r][c];if(v===1)e.classList.add('block');else if(v===2)e.classList.add('bombLocked');else if(v===3)e.classList.add('bombOpen');if(suggestion?.preview?.some(p=>p.r===r&&p.c===c))e.classList.add('suggest');e.title=String.fromCharCode(65+c)+(r+1);e.onclick=()=>{board[r][c]=tool==='block'?1:tool==='bombLocked'?2:tool==='bombOpen'?3:0;suggestion=null;renderBoard();updateCounts()};boardEl.appendChild(e)}updateCounts(false)}
function renderPicker(){const p=$('piecePicker');p.innerHTML='';IDS.forEach(id=>{const b=document.createElement('button');b.className='piece-button';b.title=SHAPES[id].name;b.appendChild(preview(id));b.onclick=()=>{slots[activeSlot]=id;slotOri[activeSlot]=0;renderSlots();updateCounts()};p.appendChild(b)})}
function renderSlots(){const p=$('pieceSlots');p.innerHTML='';slots.forEach((id,i)=>{const b=document.createElement('div');b.className='piece-slot'+(i===activeSlot?' active':'');b.onclick=()=>{activeSlot=i;renderSlots()};const l=document.createElement('span');l.className='slot-label';l.textContent='Фигура '+(i+1);b.appendChild(l);if(id){b.appendChild(preview(id,slotOri[i]));const x=document.createElement('button');x.className='text-btn';x.textContent='×';x.style.cssText='position:absolute;right:4px;top:2px';x.onclick=e=>{e.stopPropagation();slots[i]=null;slotOri[i]=0;renderSlots();updateCounts()};b.appendChild(x)}else{const t=document.createElement('span');t.textContent='выбрать';t.style.color='#66899c';b.appendChild(t)}p.appendChild(b)});renderOrientation()}
function renderOrientation(){const w=$('orientation');w.innerHTML='';const id=slots[activeSlot];if(!id)return;ORIENTS[id].forEach((_,i)=>{const b=document.createElement('button');b.textContent=`${i*90}°`;b.className=slotOri[activeSlot]===i?'active':'';b.onclick=()=>{slotOri[activeSlot]=i;renderSlots();updateCounts()};w.appendChild(b)})}
function countLines(b){const rows=[],cols=[];for(let r=0;r<10;r++)if(b[r].every(Boolean))rows.push(r);for(let c=0;c<10;c++){let ok=true;for(let r=0;r<10;r++)if(!b[r][c])ok=false;if(ok)cols.push(c)}return{rows,cols,total:rows.length+cols.length}}
function updateCounts(resetStats=true){const filled=board.flat().filter(Boolean).length;$('filledCount').textContent=filled;$('lineCount').textContent=countLines(board).total;let m=0;slots.forEach((id,i)=>{if(id)m+=placements(board,id,slotOri[i]).length});$('currentMoves').textContent=m;if(resetStats){$('bestScore').textContent='—';$('resultMoves').textContent='—'}}
function setTool(t){tool=t;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t))}document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function clearLines(b){const q=countLines(b),n=b.map(r=>r.slice()),affected=new Set();q.rows.forEach(r=>{for(let c=0;c<10;c++)affected.add(`${r},${c}`)});q.cols.forEach(c=>{for(let r=0;r<10;r++)affected.add(`${r},${c}`)});for(const k of affected){const [r,c]=k.split(',').map(Number);if(n[r][c]===2)n[r][c]=3;else if(n[r][c]===3)n[r][c]=0;else n[r][c]=0}return{board:n,total:q.total}}
function canPlace(b,cells,r,c){return cells.every(([x,y])=>{const R=r+y,C=c+x;return R>=0&&R<10&&C>=0&&C<10&&!b[R][C]})}
function place(b,cells,r,c){const n=b.map(x=>x.slice());cells.forEach(([x,y])=>n[r+y][c+x]=1);return n}
function placements(b,id,o){const cells=ORIENTS[id][o].cells,maxX=Math.max(...cells.map(p=>p[0])),maxY=Math.max(...cells.map(p=>p[1])),out=[];for(let r=0;r<=9-maxY;r++)for(let c=0;c<=9-maxX;c++)if(canPlace(b,cells,r,c))out.push({r,c,cells});return out}
function openness(b){let s=0;for(let r=0;r<10;r++){const n=b[r].filter(v=>!v).length;s+=n*n}for(let c=0;c<10;c++){let n=0;for(let r=0;r<10;r++)if(!b[r][c])n++;s+=n*n}return s}
function futureMoves(b){let sum=0;IDS.forEach(id=>{let best=0;for(let o=0;o<ORIENTS[id].length;o++)best=Math.max(best,placements(b,id,o).length);sum+=best});return sum/IDS.length}
function holes(b){let p=0;for(let r=0;r<10;r++)for(let c=0;c<10;c++)if(!b[r][c]){let n=0;for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const R=r+dr,C=c+dc;if(R>=0&&R<10&&C>=0&&C<10&&!b[R][C])n++}if(n===0)p+=8;else if(n===1)p+=2}return p}
function score(b,lines){const w=+$('survivalWeight').value/100,fa=$('futureAware').checked,ba=$('bombAware').checked,free=100-b.flat().filter(Boolean).length,f=fa?futureMoves(b):0;let bomb=0;if(ba)for(const row of b)for(const v of row){if(v===2)bomb-=.3;if(v===3)bomb+=2}return lines*1400+w*(f*10+openness(b)*.5-holes(b)*2+bomb*8)+(1-w)*free}
function permutations(a){const out=[],used=Array(a.length).fill(false),cur=[];function go(){if(cur.length===a.length){out.push(cur.slice());return}for(let i=0;i<a.length;i++)if(!used[i]){used[i]=true;cur.push(a[i]);go();cur.pop();used[i]=false}}go();return out}
function showResult(html,ok=true){const e=$('result');e.className='result'+(ok?'':' empty');e.innerHTML=html}
function solve(){const selected=slots.map((id,i)=>id?{id,o:slotOri[i],slot:i}:null).filter(Boolean);if(!selected.length){showResult('<strong>Сначала выбери три фигуры.</strong>',false);return}let best=null;for(const order of permutations(selected)){let layer=[{b:board.map(r=>r.slice()),steps:[],lines:0}];for(const item of order){const next=[];for(const st of layer)for(const p of placements(st.b,item.id,item.o)){const cl=clearLines(place(st.b,p.cells,p.r,p.c));next.push({b:cl.board,steps:st.steps.concat([{...item,r:p.r,c:p.c,lines:cl.total}]),lines:st.lines+cl.total})}next.sort((a,b)=>score(b.b,b.lines)-score(a.b,a.lines));layer=next.slice(0,80);if(!layer.length)break}for(const st of layer){const sc=score(st.b,st.lines);if(!best||sc>best.score)best={...st,score:sc}}}if(!best){showResult('<strong>Для выбранных фигур сейчас нет допустимой последовательности.</strong>',false);return}suggestion={preview:[]};let temp=board.map(r=>r.slice());best.steps.forEach((s,i)=>{ORIENTS[s.id][s.o].cells.forEach(([x,y])=>suggestion.preview.push({r:s.r+y,c:s.c+x,step:i}));temp=clearLines(place(temp,ORIENTS[s.id][s.o].cells,s.r,s.c)).board});renderBoard();$('bestScore').textContent=Math.round(best.score);$('resultMoves').textContent=Math.round(futureMoves(best.b));let html='<strong class="good">Последовательность найдена</strong><ol class="move-list">';best.steps.forEach((s,i)=>{const pos=String.fromCharCode(65+s.c)+(s.r+1);html+=`<li><b>${SHAPES[s.id].name}</b> → ${pos}${s.lines?` <span class="good">+${s.lines} линий</span>`:''}</li>`});html+='</ol><p>Зелёной рамкой показаны клетки фигур в рекомендуемой последовательности.</p>';showResult(html,true)}
$('solve').onclick=solve;$('clearPieces').onclick=()=>{slots=[null,null,null];slotOri=[0,0,0];renderSlots();updateCounts()};$('clearAll').onclick=clearAll;$('demoBoard').onclick=demo;$('hideScreenshot').onclick=()=>{$('screenshotPanel').hidden=true};
function clearAll(){board=emptyBoard();slots=[null,null,null];slotOri=[0,0,0];suggestion=null;lastImage=null;$('imageInput').value='';$('imageInput2').value='';$('scanAgain').disabled=true;$('scanAgain2').disabled=true;$('scanStatus').textContent='Готов';renderBoard();renderSlots();showResult('<strong>Поле очищено.</strong><p>Загрузи новый скриншот или заполни его вручную.</p>',true)}
function setImage(file){if(!file)return;lastImage=file;$('scanAgain').disabled=false;$('scanAgain2').disabled=false;const url=URL.createObjectURL(file);$('screenshotPreview').src=url;$('screenshotPanel').hidden=false;analyzeImage(file)}
$('imageInput').onchange=e=>setImage(e.target.files?.[0]);$('imageInput2').onchange=e=>setImage(e.target.files?.[0]);$('scanAgain').onclick=()=>lastImage&&analyzeImage(lastImage);$('scanAgain2').onclick=()=>lastImage&&analyzeImage(lastImage);
async function analyzeImage(file){$('scanStatus').textContent='Распознаю…';try{const img=await loadImage(file);const rect=findBoardRect(img);board=readBoard(img,rect);const pieces=readPieces(img);slots=[null,null,null];slotOri=[0,0,0];pieces.forEach((p,i)=>{if(i<3&&p){slots[i]=p.id;slotOri[i]=p.o}});suggestion=null;renderBoard();renderSlots();const occupied=board.flat().filter(Boolean).length;const named=pieces.filter(Boolean).length;$('scanStatus').textContent=`Готово: ${occupied} клеток, ${named}/3 фигур`;showResult(`<strong>Скриншот распознан.</strong><p>Найдено: ${occupied} занятых клеток и ${named} из 3 фигур. Проверь результат на поле справа.</p>`,true)}catch(err){console.error(err);$('scanStatus').textContent='Ошибка распознавания';showResult('<strong>Не удалось выполнить распознавание.</strong><p>Попробуй другой скриншот или исправь поле вручную.</p>',false)}}
function loadImage(file){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>{URL.revokeObjectURL(img.src);res(img)};img.onerror=rej;img.src=URL.createObjectURL(file)})}
function pixelData(ctx,x,y,w,h){return ctx.getImageData(Math.max(0,Math.floor(x)),Math.max(0,Math.floor(y)),Math.max(1,Math.floor(w)),Math.max(1,Math.floor(h))).data}
function vivid(R,G,B){const mx=Math.max(R,G,B),mn=Math.min(R,G,B);return mx>105&&(mx-mn)>70}
function findBoardRect(img){const w=img.naturalWidth,h=img.naturalHeight,cv=document.createElement('canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});cv.width=w;cv.height=h;ctx.drawImage(img,0,0);let best=null;for(let y=0;y<Math.min(h*.22,180);y++){let start=-1;for(let x=0;x<w*.7;x++){const d=ctx.getImageData(x,y,1,1).data;const ok=d[0]>=75&&d[0]<=150&&d[1]>=100&&d[1]<=175&&d[2]>=120&&d[2]<=205&&(d[2]-d[0])<100;if(ok&&start<0)start=x;if((!ok||x===Math.floor(w*.7)-1)&&start>=0){const end=ok?x:x-1;if(end-start>250&&(!best||end-start>best.len))best={x:start,y,w:end-start+1,len:end-start+1};start=-1}}}if(best){let x=best.x,y=best.y;let size=best.len;return{x:x+6,y:y+6,w:size-12,h:size-12}}return{x:w*.041,y:h*.035,w:w*.506,h:h*.91}}
function readBoard(img,rect){const cv=document.createElement('canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});cv.width=img.naturalWidth;cv.height=img.naturalHeight;ctx.drawImage(img,0,0);const out=emptyBoard(),cw=rect.w/10,ch=rect.h/10;for(let r=0;r<10;r++)for(let c=0;c<10;c++){const x=rect.x+c*cw+cw*.12,y=rect.y+r*ch+ch*.12,w=cw*.76,h=ch*.76,d=pixelData(ctx,x,y,w,h);let n=d.length/4,v=0,gray=0,mean=0,variance=0;for(let i=0;i<d.length;i+=4){const R=d[i],G=d[i+1],B=d[i+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B);mean+=mx;variance+=(mx*mx);if(vivid(R,G,B))v++;if(mx-mn<45&&mx>55)gray++}mean/=n;variance=variance/n-mean*mean;if(v/n>.08)out[r][c]=1;else if(gray/n>.025&&variance>100)out[r][c]=2}return out}
function readPieces(img){const cv=document.createElement('canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});cv.width=img.naturalWidth;cv.height=img.naturalHeight;ctx.drawImage(img,0,0);const w=img.naturalWidth,h=img.naturalHeight;const regions=[{x:.64,y:.07,w:.115,h:.23},{x:.735,y:.07,w:.115,h:.23},{x:.83,y:.07,w:.115,h:.23}];return regions.map(q=>{const x=Math.floor(w*q.x),y=Math.floor(h*q.y),rw=Math.floor(w*q.w),rh=Math.floor(h*q.h),d=pixelData(ctx,x,y,rw,rh),pts=[];for(let j=0;j<rh;j++)for(let i=0;i<rw;i++){const k=(j*rw+i)*4,R=d[k],G=d[k+1],B=d[k+2];if(vivid(R,G,B))pts.push([i,j])}if(!pts.length)return null;const minx=Math.min(...pts.map(p=>p[0])),maxx=Math.max(...pts.map(p=>p[0])),miny=Math.min(...pts.map(p=>p[1])),maxy=Math.max(...pts.map(p=>p[1]));return matchPiece(ctx,x+minx,y+miny,maxx-minx+1,maxy-miny+1)})}
function matchPiece(ctx,x,y,w,h){let best=null,bestScore=-1;for(const id of IDS)for(let o=0;o<ORIENTS[id].length;o++){const cells=ORIENTS[id][o].cells,W=Math.max(...cells.map(p=>p[0]))+1,H=Math.max(...cells.map(p=>p[1]))+1;const sx=w/W,sy=h/H,cell=(sx+sy)/2;let score=0;for(let gy=0;gy<H;gy++)for(let gx=0;gx<W;gx++){const expected=cells.some(p=>p[0]===gx&&p[1]===gy),cx=x+(gx+.5)*sx,cy=y+(gy+.5)*sy,patch=pixelData(ctx,cx-cell*.28,cy-cell*.28,cell*.56,cell*.56);let hit=0,n=patch.length/4;for(let i=0;i<patch.length;i+=4)if(vivid(patch[i],patch[i+1],patch[i+2]))hit++;const occ=hit/n;score+=expected?occ:(1-occ)*.7}score-=Math.abs(sx-sy)/Math.max(sx,sy)*.4;if(score>bestScore){bestScore=score;best={id,o}}}return bestScore>.75?best:null}
function demo(){board=emptyBoard();[[0,0],[1,0],[0,1],[1,1],[0,4],[0,5],[0,6],[0,7],[8,8],[8,9],[9,8],[5,2],[6,2],[7,2],[7,3],[3,8],[4,8],[5,8]].forEach(([r,c])=>board[r][c]=1);board[3][3]=2;board[6][0]=2;board[9][1]=2;board[5][5]=2;slots=['L','square','S'];slotOri=[0,0,0];suggestion=null;renderBoard();renderSlots();showResult('<strong>Демо загружено.</strong><p>Теперь нажми «Найти лучший ход».</p>',true)}
renderPicker();renderSlots();renderBoard();
