const SIZE=10;
const SHAPES={
 square:{name:'Квадрат 2×2',cells:[[0,0],[1,0],[0,1],[1,1]],color:'yellow'},
 line4:{name:'Линия 4',cells:[[0,0],[0,1],[0,2],[0,3]],color:'blue'},
 L:{name:'L',cells:[[0,0],[0,1],[0,2],[1,2]],color:'orange'},
 Z:{name:'Z',cells:[[0,0],[1,0],[1,1],[2,1]],color:'red'},
 J:{name:'J',cells:[[1,0],[1,1],[1,2],[0,2]],color:'pink'},
 S:{name:'S',cells:[[1,0],[2,0],[0,1],[1,1]],color:'green'},
 T:{name:'T',cells:[[0,0],[1,0],[2,0],[1,1]],color:'purple'}
};
const SHAPE_IDS=Object.keys(SHAPES);
let board=Array.from({length:SIZE},()=>Array(SIZE).fill(0)),tool='block',slots=[null,null,null],activeSlot=0,lastImage=null,suggestion=null;
const ORIENTS={};
function rotate(c){let o=c.map(([x,y])=>[y,-x]),mx=Math.min(...o.map(p=>p[0])),my=Math.min(...o.map(p=>p[1]));return o.map(([x,y])=>[x-mx,y-my])}
function key(c){return JSON.stringify(c.slice().sort((a,b)=>a[1]-b[1]||a[0]-b[0]))}
function orientations(c){let out=[],cur=c;for(let i=0;i<4;i++){let k=key(cur);if(!out.some(x=>x.key===k))out.push({cells:cur,key:k});cur=rotate(cur)}return out}
for(const id of SHAPE_IDS)ORIENTS[id]=orientations(SHAPES[id].cells);
const $=id=>document.getElementById(id), boardEl=$('board'), resultEl=$('result');
function preview(id,o=0){const cells=ORIENTS[id][o].cells,w=Math.max(...cells.map(p=>p[0]))+1,h=Math.max(...cells.map(p=>p[1]))+1,d=document.createElement('div');d.className='shape '+SHAPES[id].color;d.style.gridTemplateColumns=`repeat(${w},11px)`;d.style.gridTemplateRows=`repeat(${h},11px)`;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=document.createElement('i');if(cells.some(p=>p[0]===x&&p[1]===y))d.appendChild(i);else{d.appendChild(i);i.style.visibility='hidden'}}return d}
function renderBoard(){boardEl.innerHTML='';let filled=0;for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){let e=document.createElement('div');e.className='cell';let v=board[r][c];if(v===1){e.classList.add('block');filled++}if(v===2){e.classList.add('bombLocked');filled++}if(v===3){e.classList.add('bombOpen');filled++}if(suggestion?.preview?.some(p=>p.r===r&&p.c===c))e.classList.add('suggest');e.onclick=()=>{board[r][c]=tool==='block'?1:tool==='bombLocked'?2:tool==='bombOpen'?3:0;suggestion=null;renderBoard();updateCounts()};boardEl.appendChild(e)}$('filledCount').textContent=filled;$('lineCount').textContent=countLines(board).total}
function renderPicker(){let p=$('piecePicker');p.innerHTML='';SHAPE_IDS.forEach(id=>{let b=document.createElement('button');b.className='piece-button';b.title=SHAPES[id].name;b.appendChild(preview(id));b.onclick=()=>{slots[activeSlot]=id;slots[activeSlot+'_ori']=0;renderSlots()};p.appendChild(b)})}
function renderSlots(){let p=$('pieceSlots');p.innerHTML='';slots.forEach((id,i)=>{let b=document.createElement('div');b.className='piece-slot'+(i===activeSlot?' active':'');b.onclick=()=>{activeSlot=i;renderSlots()};let l=document.createElement('span');l.className='slot-label';l.textContent='Фигура '+(i+1);b.appendChild(l);if(id){b.appendChild(preview(id,slots[i+'_ori']||0));let x=document.createElement('button');x.className='text-btn';x.textContent='×';x.style.cssText='position:absolute;right:4px;top:2px';x.onclick=e=>{e.stopPropagation();slots[i]=null;delete slots[i+'_ori'];renderSlots();updateCounts()};b.appendChild(x)}else{let t=document.createElement('span');t.textContent='выбрать';t.style.color='#66899c';b.appendChild(t)}p.appendChild(b)};renderOrientation()}
function renderOrientation(){let wrap=$('orientation');wrap.innerHTML='';let id=slots[activeSlot];if(!id)return;ORIENTS[id].forEach((o,i)=>{let b=document.createElement('button');b.textContent=`${i*90}°`;b.className=(slots[activeSlot+'_ori']||0)===i?'active':'';b.onclick=()=>{slots[activeSlot+'_ori']=i;renderSlots()};wrap.appendChild(b)})}
function updateCounts(){let n=0;for(const row of board)for(const v of row)if(v)n++;$('filledCount').textContent=n;$('lineCount').textContent=countLines(board).total;let ids=slots.filter(Boolean);let m=ids.reduce((s,id,i)=>s+bestOrientationMoves(board,id,slots[i+'_ori']||0),0);$('currentMoves').textContent=m}
function setTool(t){tool=t;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t))}
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function countLines(b){let rows=[],cols=[];for(let r=0;r<SIZE;r++)if(b[r].every(Boolean))rows.push(r);for(let c=0;c<SIZE;c++){let ok=true;for(let r=0;r<SIZE;r++)if(!b[r][c])ok=false;if(ok)cols.push(c)}return{rows,cols,total:rows.length+cols.length}}
function clearLines(b){let q=countLines(b),n=b.map(r=>r.slice()),affected=new Set();q.rows.forEach(r=>{for(let c=0;c<SIZE;c++)affected.add(r+','+c)});q.cols.forEach(c=>{for(let r=0;r<SIZE;r++)affected.add(r+','+c)});for(const k of affected){let [r,c]=k.split(',').map(Number);if(n[r][c]===2)n[r][c]=3;else if(n[r][c]===3)n[r][c]=0;else n[r][c]=0}return{board:n,total:q.total,rows:q.rows,cols:q.cols}}
function canPlace(b,cells,r,c){return cells.every(([x,y])=>{let R=r+y,C=c+x;return R>=0&&R<SIZE&&C>=0&&C<SIZE&&!b[R][C]})}
function place(b,cells,r,c){let n=b.map(x=>x.slice());cells.forEach(([x,y])=>n[r+y][c+x]=1);return n}
function placements(b,id,o){let cells=ORIENTS[id][o].cells,maxX=Math.max(...cells.map(p=>p[0])),maxY=Math.max(...cells.map(p=>p[1])),out=[];for(let r=0;r<SIZE-maxY;r++)for(let c=0;c<SIZE-maxX;c++)if(canPlace(b,cells,r,c))out.push({r,c,cells});return out}
function bestOrientationMoves(b,id,o){return placements(b,id,o).length}
function openness(b){let s=0;for(let r=0;r<SIZE;r++){let n=b[r].filter(v=>!v).length;s+=n*n}for(let c=0;c<SIZE;c++){let n=0;for(let r=0;r<SIZE;r++)if(!b[r][c])n++;s+=n*n}return s}
function futureMoves(b){let sum=0;for(const id of SHAPE_IDS){let best=0;for(let o=0;o<ORIENTS[id].length;o++)best=Math.max(best,placements(b,id,o).length);sum+=best}return sum/SHAPE_IDS.length}
function holes(b){let p=0;for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(!b[r][c]){let n=0;for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){let R=r+dr,C=c+dc;if(R>=0&&R<SIZE&&C>=0&&C<SIZE&&!b[R][C])n++}if(n===0)p+=8;else if(n===1)p+=2}return p}
function score(b,lines){let w=+$('survivalWeight').value/100,fa=$('futureAware').checked,ba=$('bombAware').checked,free=100-b.flat().filter(Boolean).length,f=fa?futureMoves(b):0,bomb=0;if(ba){for(const row of b)for(const v of row){if(v===2)bomb-=.3;if(v===3)bomb+=2}}return lines*1400+w*(f*10+openness(b)*.5-holes(b)*2+bomb*8)+(1-w)*free}
function permutations(a){let out=[],used=Array(a.length).fill(false),cur=[];function go(){if(cur.length===a.length){out.push(cur.slice());return}for(let i=0;i<a.length;i++)if(!used[i]){used[i]=true;cur.push(a[i]);go();cur.pop();used[i]=false}}go();return out}
function solve(){let selected=slots.map((id,i)=>id?{id,o:slots[i+'_ori']||0,slot:i}:null).filter(Boolean);if(!selected.length){result('Выбери хотя бы одну фигуру.',false);return}let best=null;for(const orderIds of permutations(selected)){let layer=[{b:board.map(r=>r.slice()),steps:[],lines:0}];for(const item of orderIds){let next=[];for(const st of layer)for(const p of placements(st.b,item.id,item.o)){let cl=clearLines(place(st.b,p.cells,p.r,p.c));next.push({b:cl.board,steps:st.steps.concat([{...item,r:p.r,c:p.c,lines:cl.total}]),lines:st.lines+cl.total})}next.sort((a,b)=>score(b.b,b.lines)-score(a.b,a.lines));layer=next.slice(0,100);if(!layer.length)break}for(const st of layer){let sc=score(st.b,st.lines);if(!best||sc>best.score)best={...st,score:sc}}}if(!best){result('Для этих фигур сейчас нет допустимого хода.',false);return}suggestion=makePreview(best.steps);renderBoard();$('bestScore').textContent=Math.round(best.score);$('resultMoves').textContent=Math.round(futureMoves(best.b));let html='<strong class="good">Последовательность найдена</strong><ul class="move-list">';best.steps.forEach((s,i)=>{let pos=String.fromCharCode(65+s.c)+(s.r+1);html+=`<li><b>${i+1}. ${SHAPES[s.id].name}</b> → ${pos}${s.lines?` <span class="good">+${s.lines} линий</span>`:''}</li>`});html+='</ul><p>Зелёная рамка на поле показывает клетки рекомендованной последовательности.</p>';result(html,true,true)}
function makePreview(steps){let b=board.map(r=>r.slice()),p=[];steps.forEach((s,i)=>{ORIENTS[s.id][s.o].cells.forEach(([x,y])=>p.push({r:s.r+y,c:s.c+x,step:i}));b=clearLines(place(b,ORIENTS[s.id][s.o].cells,s.r,s.c)).board});return{preview:p}}
function result(html,ok=true,rich=false){resultEl.className='result'+(ok?'':' empty');resultEl.innerHTML=rich?html:`<strong>${html}</strong>`}
$('solve').onclick=solve;$('clearBoard').onclick=()=>{board=Array.from({length:SIZE},()=>Array(SIZE).fill(0));suggestion=null;renderBoard();updateCounts()};$('clearPieces').onclick=()=>{slots=[null,null,null];renderSlots();updateCounts()};$('demoBoard').onclick=demo;
$('hideScreenshot').onclick=()=>$('screenshotPanel').hidden=true;$('scanAgain').onclick=()=>lastImage&&analyzeImage(lastImage);
$('imageInput').onchange=e=>{let f=e.target.files?.[0];if(f){lastImage=f;let url=URL.createObjectURL(f);$('screenshotPreview').src=url;$('screenshotPanel').hidden=false;analyzeImage(f)}};
async function analyzeImage(file){$('scanStatus').textContent='Сканирую…';let img=new Image();img.onload=()=>{try{let rect=findBoardRect(img);let cells=readBoard(img,rect);board=cells;let found=readPieces(img);found.forEach((id,i)=>{if(i<3){slots[i]=id;slots[i+'_ori']=detectOrientation(img,id,i)}});renderBoard();renderSlots();updateCounts();$('scanStatus').textContent=`Распознано: ${countOccupied(board)} клеток`;result(`<b>Скриншот обработан.</b><p>Проверь поле и фигуры — распознавание можно вручную поправить.</p>`,true,true)}catch(e){console.error(e);$('scanStatus').textContent='Нужна ручная проверка';result('Не удалось надёжно распознать скриншот. Поле всё равно можно отметить вручную.',false)}};img.src=URL.createObjectURL(file)}
function findBoardRect(img){let w=img.naturalWidth,h=img.naturalHeight,s=Math.min(w,h),left=w*.035,top=h*.125,size=Math.min(w*.515,h*.825); // tuned for official event layout
return{x:left,y:top,w:size,h:size}}
function readBoard(img,rect){let cv=document.createElement('canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});cv.width=img.naturalWidth;cv.height=img.naturalHeight;ctx.drawImage(img,0,0);let out=Array.from({length:10},()=>Array(10).fill(0)),cw=rect.w/10,ch=rect.h/10;for(let r=0;r<10;r++)for(let c=0;c<10;c++){let x=rect.x+c*cw+cw*.2,y=rect.y+r*ch+ch*.2,w=cw*.6,h=ch*.6,d=ctx.getImageData(Math.max(0,x),Math.max(0,y),Math.max(1,w),Math.max(1,h)).data;let sat=0,bright=0,gray=0,n=d.length/4;for(let i=0;i<d.length;i+=4){let R=d[i],G=d[i+1],B=d[i+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B);sat+=mx-mn;bright+=mx;if(mx-mn<24&&mx>65)gray++}sat/=n;bright/=n;gray/=n;if(sat>48&&bright>70)out[r][c]=1;else if(gray>.07&&bright>60)out[r][c]=2}return out}
function countOccupied(b){return b.flat().filter(Boolean).length}
function readPieces(img){let cv=document.createElement('canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});cv.width=img.naturalWidth;cv.height=img.naturalHeight;ctx.drawImage(img,0,0);let regions=[{x:.675,y:.20,w:.075,h:.13},{x:.765,y:.20,w:.075,h:.13},{x:.855,y:.20,w:.075,h:.13}],found=[];for(const q of regions){let x=img.naturalWidth*q.x,y=img.naturalHeight*q.y,w=img.naturalWidth*q.w,h=img.naturalHeight*q.h,d=ctx.getImageData(x,y,w,h).data;let pts=[];for(let j=0;j<h;j++)for(let i=0;i<w;i++){let k=(j*w+i)*4,R=d[k],G=d[k+1],B=d[k+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B);if(mx-mn>80&&mx>100)pts.push([i,j])}if(!pts.length)continue;let minx=Math.min(...pts.map(p=>p[0])),maxx=Math.max(...pts.map(p=>p[0])),miny=Math.min(...pts.map(p=>p[1])),maxy=Math.max(...pts.map(p=>p[1]));let shape=normalizePixels(pts,minx,maxx,miny,maxy);let id=matchShape(shape);if(id)found.push(id)}return found}
function normalizePixels(pts,minx,maxx,miny,maxy){let W=maxx-minx+1,H=maxy-miny+1,grid=Array.from({length:4},()=>Array(4).fill(0));for(const [x,y] of pts){let gx=Math.min(3,Math.floor((x-minx)/Math.max(1,W)*4)),gy=Math.min(3,Math.floor((y-miny)/Math.max(1,H)*4));grid[gy][gx]=1}return grid}
function matchShape(grid){let best=null,bs=1e9;for(const id of SHAPE_IDS){for(let o=0;o<ORIENTS[id].length;o++){let c=ORIENTS[id][o].cells,w=Math.max(...c.map(p=>p[0]))+1,h=Math.max(...c.map(p=>p[1]))+1,model=Array.from({length:4},()=>Array(4).fill(0));c.forEach(([x,y])=>model[Math.floor(y*4/h)][Math.floor(x*4/w)]=1);let d=0;for(let y=0;y<4;y++)for(let x=0;x<4;x++)if(grid[y][x]!==model[y][x])d++;if(d<bs){bs=d;best=id}}}return bs<=5?best:null}
function detectOrientation(img,id,slot){return 0}
function demo(){board=Array.from({length:10},()=>Array(10).fill(0));[[0,0],[1,0],[0,1],[1,1],[4,0],[5,0],[6,0],[7,0],[9,9],[8,9],[7,8],[6,8],[2,5],[2,6],[2,7],[3,7],[8,3],[8,4],[8,5]].forEach(([r,c])=>board[r][c]=1);board[4][4]=2;board[7][1]=2;slots=['L','Z','line4'];slots.forEach((id,i)=>slots[i+'_ori']=0);renderBoard();renderSlots();updateCounts();result('<b>Демо загружено.</b><p>Нажми «Найти лучший ход».</p>',true,true)}
renderPicker();renderSlots();renderBoard();updateCounts();
